<?php

namespace App\Models\Tenant;

use App\Traits\BelongsToTenant;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class QuickAccessLink extends Model
{
    use BelongsToTenant;

    protected $fillable = [
        'tenant_id', 'person_type', 'person_id',
        'token', 'pin_hash', 'pin_enabled', 'is_active', 'last_used_at',
    ];

    protected $casts = [
        'pin_enabled'  => 'boolean',
        'is_active'    => 'boolean',
        'last_used_at' => 'datetime',
    ];

    protected $hidden = ['pin_hash'];

    protected static function booted(): void
    {
        static::creating(function (QuickAccessLink $link) {
            if (empty($link->token)) {
                $link->token = static::generateUniqueToken();
            }
        });
    }

    /**
     * 24-char mixed-case alphanumeric via Str::random() — Laravel's
     * implementation uses random_bytes() under the hood, cryptographically
     * secure. ~142 bits of entropy at this length: well above the ~128-bit
     * threshold generally considered unbreakable by brute force, chosen
     * with deliberate margin since this token is a PERMANENT, reusable
     * credential (unlike the one-off DocumentShareLink token), while still
     * being short enough to paste into an SMS/WhatsApp message.
     */
    public static function generateUniqueToken(): string
    {
        do {
            $token = Str::random(24);
        } while (static::withoutGlobalScope('tenant')->where('token', $token)->exists());

        return $token;
    }

    public function person(): ?Model
    {
        return $this->person_type::withoutGlobalScope('tenant')->find($this->person_id);
    }

    public function setPin(string $rawPin): void
    {
        $this->update(['pin_hash' => Hash::make($rawPin)]);
    }

    public function verifyPin(string $rawPin): bool
    {
        return $this->pin_hash && Hash::check($rawPin, $this->pin_hash);
    }

    public function needsPinSetup(): bool
    {
        return $this->pin_enabled && !$this->pin_hash;
    }

    /**
     * Regeneration = a genuinely new row with a new token, old one deleted
     * outright — never an in-place token swap. This guarantees the old
     * link is provably dead the instant regeneration happens, with no
     * window where a cached/bookmarked old link could still resolve to
     * anything (an UPDATE could theoretically be read via a stale cache
     * or replica lag; a DELETE cannot).
     */
    /**
     * $initiatedBySelf distinguishes "you regenerated your own link" from
     * "your organization regenerated it for you" in the resulting
     * notification — without this, a person force-regenerated by their
     * tenant (e.g. after reporting a compromised link) would see an
     * identical, ambiguous message to one they triggered themselves,
     * which is a real clarity gap for a security-relevant event.
     */
    public static function regenerateFor(string $personType, int $personId, int $tenantId, bool $initiatedBySelf = true): self
    {
        static::withoutGlobalScope('tenant')
            ->where('person_type', $personType)
            ->where('person_id', $personId)
            ->where('tenant_id', $tenantId)
            ->delete();

        $link = static::create([
            'tenant_id'   => $tenantId,
            'person_type' => $personType,
            'person_id'   => $personId,
        ]);

        $person = $link->person();
        if ($person) {
            app(\App\Services\Notifications\NotificationDispatchService::class)->notify(
                notifiable: $person,
                category: 'security',
                notificationType: 'quick_access_link_regenerated',
                templateKey: 'quick_access_link_regenerated',
                placeholders: [
                    'user_name' => $person->name,
                    'initiator' => $initiatedBySelf ? 'You' : 'Your organization',
                ],
                priority: 'high',
                actionUrl: null,
                actionLabel: null,
                subject: $link,
                tenantId: $tenantId,
            );
        }

        return $link;
    }
}